### ISSUE TITLE
Enable log rotation to avoid running out of disk space

### ISSUE THREAD

**Issue by podhrmic** [GaloisInc/BESSPIN-Tool-Suite#1085]
Currently, the logs take around 1.5 GB/week. 
Which means we *could* run out of disk space in several weeks of uptime.
Add log-rotation to avoid this possibility.

**Comment by podhrmic** [comment]
@dmzimmerman would you mind adding the proper logrotate config?

**Comment by podhrmic** [comment]
A second task is to add NoRsyslog debian into https://github.com/GaloisInc/BESSPIN-LFS/tree/develop

How?

In nix-shell do:
```
$ env | grep RSYSLOG
BESSPIN_GFE_DEBIAN_VCU118_NO_RSYSLOG=/nix/store/mvxi42b5ydax0x44msffn7hinwqdq75k-riscv-bbl
```
and then upload the resulting OS image as `debian_noRsyslog.elf` into GFE/osImages/vcu118 folder

**Comment by dmzimmerman** [comment]
Yup, I'll take care of both of these.

**Comment by podhrmic** [comment]
Seems like using the noRsyslog image solved the problem - after 16 hours of uptime, the disk usage looks the same as right after boot (solid 30%). Or do you still want to add the proper log rotation config?

**Comment by dmzimmerman** [comment]
I don't think there's any need for it at this point.
