### ISSUE TITLE
Autostart ignition after boot (no user input needed)

### ISSUE THREAD

**Issue by lolsborn** [GaloisInc/BESSPIN-Tool-Suite#1167]
Parent issue #1150

**Comment by podhrmic** [comment]
@EthanJamesLew @lolsborn does it star automatically now?

**Comment by lolsborn** [comment]
It does, but you still have to login to windows first.  If that's acceptable then I think this is done.  If not we need to enable auto-login.

**Comment by podhrmic** [comment]
Lets enable auto login please.

**Comment by lolsborn** [comment]
I went through this process to enable auto-login.  It's certainly not as easy to do as it used to be.
https://docs.microsoft.com/en-us/troubleshoot/windows-server/user-profiles-and-logon/turn-on-automatic-logon

**Comment by lolsborn** [comment]
Closing this issue as it boots up ignition on startup now.
