### ISSUE TITLE
Path to configSecurityTests should be configurable

### ISSUE THREAD

**Issue by brooksdavis** [GaloisInc/BESSPIN-Tool-Suite#1177]
When self-scoring hardware CWEs, different platforms will have different values (e.g., p1 and p2 don't speculate so aren't vulnerable to Spectre/Meltdown). When evaluating, it would be convenient to be able to commit copies of the .ini files for each config to the repo (e.g., in `configSecureyTests-p1`, ...) but `configSecurityTests` is currently hardcoded. Allowing it to be configured or for the filenames to be configured would be helpful.

**Comment by rtadros125** [comment]
@brooksdavis I just saw this. Isn't this what `useCustomCWEsConfigsPath` and `pathToCustomCWEsConfigs` are for? What am I missing here?

**Comment by brooksdavis** [comment]
That does indeed seem to be what I'm asking for. I'm not sure how I missed that before.  Thanks.
