### ISSUE TITLE
BeamNG Connection Timeouts

### ISSUE THREAD

**Issue by dmzimmerman** [GaloisInc/BESSPIN-Tool-Suite#1194]
Occasionally, and apparently unpredictably, the connection from ignition to BeamNG times out. This has been observed to happen anywhere from minutes to many hours after the system is brought up. When it happens, telemetry from BeamNG (GPS positions, speeds, etc.) stops. 

It could be a BeamNG issue with a known solution. Also, we might be able to mitigate it on the Python side by timing out the connection and re-establishing it.

**Comment by podhrmic** [comment]
@EthanJamesLew @lolsborn have we observed any such timeouts since upgrading the BeamNG version?

**Comment by podhrmic** [comment]
Should be fixed in a8c50e2d2fdbec11f13e9c32c9ed9ea27787b31e

**Comment by podhrmic** [comment]
Looks good - I see a reconnect message popping up relatively often in the log, but it works just fine. Open question is what happens if you are driving *and* a reconnect happen? @EthanJamesLew
