### ISSUE TITLE
Fix pedal input/joystic input detection

### ISSUE THREAD

**Issue by podhrmic** [GaloisInc/BESSPIN-Tool-Suite#1217]
Currently the detection continuously resets the simulator. Make it such if a change in the throttle/brake values is detected *and* the car is in self-driving mode, the self-driving mode is disabled.

**Comment by podhrmic** [comment]
Cherry picked the changes, should be fixed in #1214 - but needs to be tested

**Comment by podhrmic** [comment]
Works good. An open question is what happens when a hack is active - for example throttle fixed at 100%, and a driver is driving. Will the algorithm treat it as a pedal inactivity? @EthanJamesLew

**Comment by dmzimmerman** [comment]
I would hope that "pedal inactivity" means "the pedals are stuck at 0", rather than "the pedals are stuck at any particular value"... but the brake hack fixes the brakes at 0, so the same issue would apply there.

**Comment by dmzimmerman** [comment]
Is this still an open issue? (and if so, is it maybe the cause of the spurious resets we saw on Tuesday?)

**Comment by podhrmic** [comment]
I believe the original issue is fixed. The hack issue shouldn't matter as long as you are driving (moving the steering wheel).
