### ISSUE TITLE
Switch to non-compartmentalized CHERI version

### ISSUE THREAD

**Issue by podhrmic** [GaloisInc/BESSPIN-Tool-Suite#1223]
and hardcode return address to the fault handler. That should fix the ECU crashes.
Or validate whether the compartmentalized version of Cheri works as expected.

**Comment by podhrmic** [comment]
Might not be necessary after https://github.com/GaloisInc/BESSPIN-LFS/commit/df4a16296fbe0570c3ee9272156f62acde1c2ceb - testing needed

**Comment by podhrmic** [comment]
Cheri sill mysteriously crashes in real environment:
```
<<<< Fault in Task: prvCanRxTask: Compartment #12: /lib/libfreertos_tcpip.a:riscv_hal_eth.c.8.o
<<<< Fault in Task: prvCanRxTask: Compartment #11: /lib/libcyberphys.a:canlib.c.1.o
00:13:34.448 (prvCanRxTask) recv_can_message returned 6
```

**Comment by dmzimmerman** [comment]
Interesting. And it's still crashing in the Ethernet HAL... was the increased number of buffers compiled into this version?

**Comment by podhrmic** [comment]
Not relevant anymore - CHERI works now.
