### ISSUE TITLE
Hack While in Self Drive

### ISSUE THREAD

**Issue by EthanJamesLew** [GaloisInc/BESSPIN-Tool-Suite#1234]
**Summary**
Ignition may reset the scenario when being hacked in self-drive.

**Details**
* the activity monitor in ignition will see changes in the CAN packets as activity and will reset the scenario in self-drive when hacked. It will continue being hacked afterward.
* behavior needs to be defined for being hacked when in self-drive.
* it's not possible currently to "mix" the self-drive with the CAN packet inputs.

**Comment by podhrmic** [comment]
@EthanJamesLew could you please ask BeamNG folks for a feature that lets you "mix in" your input in the self-drive mode?
We want to at least know how difficult they think it would be.

**Comment by podhrmic** [comment]
FYI this is very unlikely to happen, so I am closing this as "won't implement"
