### ISSUE TITLE
Cyberphys: Force Feedback / Ignition Testing

### ISSUE THREAD

**Issue by EthanJamesLew** [GaloisInc/BESSPIN-Tool-Suite#1235]
**Summary**
* ignition hasn't been tested with the force feedback after fixing the steering wheel

**Comment by podhrmic** [comment]
Will do it today

**Comment by dmzimmerman** [comment]
Is this still an open issue?

**Comment by podhrmic** [comment]
It works as expected. Why sometimes force feedback doesn't work is not clear, and is a different issue.
