### ISSUE TITLE
CWE-761 Contains No Vulnerability

### ISSUE THREAD

**Issue by njshanahan** [GaloisInc/BESSPIN-Tool-Suite#1237]
After the modification of `test_761.c`, the test no longer contains a vulnerability. See the `develop` branch, commit b603085.

The second test part is as follows.
```c
contains_char('T');
```
The function searches the string `Search!` for the character `T`, which will not be found. Although the index `i` is incremented, the pointer `str` itself is never manipulated. Because the letter `T` is not found, the string `str` is freed on line 39. When this occurs, `str` still points to the beginning of the character buffer, meaning the correct address is freed.
```c
FREE(str);
```
To contain a vulnerability, the test would need to either increment the pointer (`str = str + 1`), as was previously done in `contains_char_malicious()`, or free `str[i]`.

FYI @austinhroach.

**Comment by rtadros125** [comment]
Thanks. Opened #1238 to fix it.
