### ISSUE TITLE
Buffer Error CWE-785 Not Generated

### ISSUE THREAD

**Issue by njshanahan** [GaloisInc/BESSPIN-Tool-Suite#1240]
I recently noticed that CWE-785 is not consistently generated when testing buffer errors. Was this test removed?

**Comment by rtadros125** [comment]
If you are doing either of the following:
- Very low number of tests
- FreeRTOS
- baremetal compiling
- custom clafer error model

Then you might not see any 785 tests. Which ones of these fit your experience so I can elaborate?

**Comment by njshanahan** [comment]
Ah, ok. I was using the bare metal compiler.

**Comment by rtadros125** [comment]
CWe 785 is about path manipulation, and baremetal compilation does not support POSIX for obvious reasons, so we just disable that CWE in baremetal configurations because no paths standards apply. Does this make sense?

**Comment by njshanahan** [comment]
Yeah that makes sense. Thanks for clarifying!
