### ISSUE TITLE
The watchdog in cyberphys needs to be thread-controlled with exitting

### ISSUE THREAD

**Issue by rtadros125** [GaloisInc/BESSPIN-Tool-Suite#862]
pre-requisite: #863 and #876 
If a target starts to exit, the watchdog should stop immediately. The commit 3510bfbd413734d62539e9d9d95dfbe6f6105143 already moves the delay in a better spot, but still, there is an assumption made between the check and the loop's body. A lock should be inserted somewhere so that all watchdogs have to be entirely turned off before the exiting procedure starts.

**Comment by podhrmic** [comment]
Doesn't seem to be a problem anymore, hence closing
